const express = require('express')
const app = express()
const Joi = require('joi')
const helmet = require('helmet')
const morgan = require('morgan')
const config = require('config')

// DEBUGGER
const startupDebugger = require('debug')('app:startup')
const dbDebugger = require('debug')('app:db')

const logger = require('./logger')

///////////////////////////////////////
// Data
///////////////////////////////////////

const courses = [
  { id: 1, name: 'course 1' },
  { id: 2, name: 'course 2' },
  { id: 3, name: 'course 3' },
  { id: 4, name: 'course 4' },
]

///////////////////////////////////////
// Middleware & Routes Handlers
///////////////////////////////////////

app.use(express.json())
app.use(morgan('tiny'))

// npm i pug
// "View page src" to see the html that is generated by PUG
// > nowadays, we rarely used template engine > we use node to build api, and the client use data from those APIs to render the front end
app.set('view engine', 'pug') // set the engine to use pug as engine
app.set('views', './views') // set default folder of the template

app.get('/', (req, res) => {
  res.render('index', { title: 'My Express App', message: 'Hey there!' })
})

///////////////////////////////////////////////////
// SERVER
///////////////////////////////////////////////////

const port = process.env.PORT || 3000

app.listen(3000, () => console.log(`Listening on port ${port}...`))
